import { type FormEvent, useState } from 'react'
import { FormField } from '../forms/FormField'
import type { AddressRequest } from '../../types/commerce'

const emptyAddress: AddressRequest = { recipient_name: '', line1: '', line2: null, city: '', state_province: '', postal_code: '', country: '', phone: null, is_default: false }
export function AddressForm({ initial = emptyAddress, onCancel, onSave }: { initial?: AddressRequest; onCancel: () => void; onSave: (value: AddressRequest) => Promise<void> }) {
  const [value, setValue] = useState<AddressRequest>(initial); const [busy, setBusy] = useState(false); const set = (key: keyof AddressRequest, next: string | boolean) => setValue((current) => ({ ...current, [key]: next }))
  const submit = async (event: FormEvent) => { event.preventDefault(); if (busy) return; setBusy(true); try { await onSave({ ...value, recipient_name: value.recipient_name.trim(), line1: value.line1.trim(), line2: value.line2?.trim() || null, city: value.city.trim(), state_province: value.state_province.trim(), postal_code: value.postal_code.trim(), country: value.country.trim(), phone: value.phone?.trim() || null }) } finally { setBusy(false) } }
  return <form className="commerce-form address-form" onSubmit={submit}><FormField id="address-recipient" label="Recipient name" value={value.recipient_name} maxLength={150} required onChange={(e) => set('recipient_name', e.target.value)} /><FormField id="address-line1" label="Address line 1" value={value.line1} maxLength={255} required onChange={(e) => set('line1', e.target.value)} /><FormField id="address-line2" label="Address line 2 (optional)" value={value.line2 ?? ''} maxLength={255} onChange={(e) => set('line2', e.target.value)} /><FormField id="address-city" label="City" value={value.city} maxLength={100} required onChange={(e) => set('city', e.target.value)} /><FormField id="address-state" label="State or province" value={value.state_province} maxLength={100} required onChange={(e) => set('state_province', e.target.value)} /><FormField id="address-postal" label="Postal code" value={value.postal_code} maxLength={20} required onChange={(e) => set('postal_code', e.target.value)} /><FormField id="address-country" label="Country" value={value.country} maxLength={100} required onChange={(e) => set('country', e.target.value)} /><FormField id="address-phone" label="Phone (optional)" value={value.phone ?? ''} maxLength={20} onChange={(e) => set('phone', e.target.value)} /><label className="checkbox-field"><input type="checkbox" checked={value.is_default} onChange={(e) => set('is_default', e.target.checked)} /> Mark as default address</label><div className="form-actions"><button className="button button-primary" disabled={busy} type="submit">{busy ? 'Saving…' : 'Save address'}</button><button className="button button-secondary" disabled={busy} type="button" onClick={onCancel}>Cancel</button></div></form>
}
