package com.handmadeart.ecommerce.dto.order;

import com.handmadeart.ecommerce.entity.CustomerOrder;
import com.handmadeart.ecommerce.entity.OrderItem;
import com.handmadeart.ecommerce.entity.OrderStatus;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Response DTO for a created or retrieved order.
 *
 * REST API Spec §9 "Create order from cart":
 *   "201 Created + OrderResponse"
 *   DTO table: "order id, item snapshots, totals, address snapshot/reference, status, timestamps"
 *
 * Address fields are the snapshot values copied at checkout time; they are never
 * a live FK to the address table (Database Design §9.3).
 * DEC-007 DEFERRED: totalAmount = subtotalAmount (no tax or delivery charge).
 */
public class OrderResponse {

    private Long orderId;
    private OrderStatus status;

    // Address snapshot (copied at checkout from Address entity)
    private String shipRecipientName;
    private String shipLine1;
    private String shipLine2;
    private String shipCity;
    private String shipStateProvince;
    private String shipPostalCode;
    private String shipCountry;
    private String shipPhone;

    private BigDecimal subtotalAmount;
    private BigDecimal totalAmount;

    private List<OrderItemResponse> items;

    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;

    public OrderResponse() {
    }

    /**
     * Build an OrderResponse from a persisted {@link CustomerOrder} and its items.
     *
     * @param order the saved order entity (id populated, timestamps generated by DB)
     * @param items the saved order items
     */
    public static OrderResponse from(CustomerOrder order, List<OrderItem> items) {
        OrderResponse dto = new OrderResponse();
        dto.orderId = order.getId();
        dto.status = order.getStatus();

        dto.shipRecipientName = order.getShipRecipientName();
        dto.shipLine1 = order.getShipLine1();
        dto.shipLine2 = order.getShipLine2();
        dto.shipCity = order.getShipCity();
        dto.shipStateProvince = order.getShipStateProvince();
        dto.shipPostalCode = order.getShipPostalCode();
        dto.shipCountry = order.getShipCountry();
        dto.shipPhone = order.getShipPhone();

        dto.subtotalAmount = order.getSubtotalAmount();
        dto.totalAmount = order.getTotalAmount();

        dto.items = items.stream()
                .map(OrderItemResponse::from)
                .collect(Collectors.toList());

        dto.createdAt = order.getCreatedAt();
        dto.updatedAt = order.getUpdatedAt();
        return dto;
    }

    // -------------------------------------------------------------------------
    // Getters
    // -------------------------------------------------------------------------

    public Long getOrderId() { return orderId; }
    public OrderStatus getStatus() { return status; }
    public String getShipRecipientName() { return shipRecipientName; }
    public String getShipLine1() { return shipLine1; }
    public String getShipLine2() { return shipLine2; }
    public String getShipCity() { return shipCity; }
    public String getShipStateProvince() { return shipStateProvince; }
    public String getShipPostalCode() { return shipPostalCode; }
    public String getShipCountry() { return shipCountry; }
    public String getShipPhone() { return shipPhone; }
    public BigDecimal getSubtotalAmount() { return subtotalAmount; }
    public BigDecimal getTotalAmount() { return totalAmount; }
    public List<OrderItemResponse> getItems() { return items; }
    public OffsetDateTime getCreatedAt() { return createdAt; }
    public OffsetDateTime getUpdatedAt() { return updatedAt; }
}
