import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { FormError } from '../components/forms/FormError'
import { LoadingState } from '../components/feedback/LoadingState'
import { useCart } from '../hooks/useCart'
import { accountService } from '../services/accountService'
import { checkoutService } from '../services/checkoutService'
import type { Address, CheckoutValidation } from '../types/commerce'
import { normalizeApiError } from '../utils/apiError'

export function CheckoutPage() {
  const { cart, isLoading: cartLoading, resetCart } = useCart(); const navigate = useNavigate(); const [addresses, setAddresses] = useState<Address[]>([]); const [selected, setSelected] = useState<number | null>(null); const [validation, setValidation] = useState<CheckoutValidation | null>(null); const [loadingAddresses, setLoadingAddresses] = useState(true); const [busy, setBusy] = useState<'validate' | 'order' | null>(null); const [error, setError] = useState<string | null>(null)
  useEffect(() => { let current = true; void accountService.listAddresses().then((data) => { if (current) setAddresses(data) }).catch((cause: unknown) => { if (current) setError(normalizeApiError(cause).message) }).finally(() => { if (current) setLoadingAddresses(false) }); return () => { current = false } }, [])
  const validate = async () => { if (!selected || busy) return; setBusy('validate'); setError(null); setValidation(null); try { setValidation(await checkoutService.validate(selected)) } catch (cause) { setError(normalizeApiError(cause).message) } finally { setBusy(null) } }
  const placeOrder = async () => { if (!selected || !validation?.valid || busy) return; setBusy('order'); setError(null); try { const order = await checkoutService.createOrder(selected); resetCart(); navigate(`/checkout/success/${order.orderId}`, { replace: true, state: { order } }) } catch (cause) { setValidation(null); setError(normalizeApiError(cause).message) } finally { setBusy(null) } }
  if (cartLoading || loadingAddresses) return <LoadingState label="Preparing checkout" />
  if (!cart || cart.items.length === 0) return <section className="state-panel"><h1>Your cart is empty</h1><p>Add a ready-made artwork before checking out.</p><Link to="/">Return to catalogue</Link></section>
  return <section className="commerce-page"><div className="page-heading"><p className="eyebrow">Secure review</p><h1>Checkout</h1></div>{error && <FormError message={error} />}<div className="checkout-layout"><div><section className="checkout-section"><h2>1. Select a delivery address</h2>{addresses.length === 0 ? <p>No saved addresses. <Link to="/account/addresses">Add an address</Link> to continue.</p> : <div className="address-options">{addresses.map((address) => <label className="address-option" key={address.id}><input type="radio" name="address" checked={selected === address.id} onChange={() => { setSelected(address.id); setValidation(null) }} /><span><strong>{address.recipient_name}</strong><br />{address.line1}, {address.city}, {address.state_province} {address.postal_code}</span></label>)}</div>}</section><section className="checkout-section"><h2>2. Validate your order</h2><p>This checks current prices, stock, and address eligibility. It does not reserve stock.</p><button className="button button-secondary" type="button" disabled={!selected || busy !== null} onClick={() => void validate()}>{busy === 'validate' ? 'Validating…' : 'Validate checkout'}</button>{validation?.valid && <p className="form-alert form-alert-success" role="status">Validation passed. Review the server-confirmed total and place your order when ready.</p>}</section><section className="checkout-section"><h2>3. Place order</h2><p>Stock and prices will be checked again by the backend.</p><button className="button button-primary" type="button" disabled={!validation?.valid || busy !== null} onClick={() => void placeOrder()}>{busy === 'order' ? 'Placing order…' : 'Place order'}</button></section></div><aside className="order-summary"><h2>Current cart</h2>{cart.items.map((item) => <div className="summary-line" key={item.itemId}><span>{item.productName} × {item.quantity}</span><strong>${Number(item.subtotal).toFixed(2)}</strong></div>)}<div className="summary-total"><span>{validation ? 'Validated total' : 'Cart total'}</span><strong>${Number(validation?.totalAmount ?? cart.total).toFixed(2)}</strong></div><p>Server-calculated; no tax or delivery fee has been added.</p></aside></div></section>
}
