import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { StatusBadge } from '../components/commerce/StatusBadge'
import { EmptyState } from '../components/feedback/EmptyState'
import { ErrorState } from '../components/feedback/ErrorState'
import { LoadingState } from '../components/feedback/LoadingState'
import { customArtworkService } from '../services/customArtworkService'
import type { CustomRequestPage, CustomRequestStatus } from '../types/customArtwork'
import { normalizeApiError } from '../utils/apiError'
import { formatDateTime } from '../utils/format'

const statusOptions: CustomRequestStatus[] = ['REQUESTED', 'UNDER_REVIEW', 'QUOTED', 'CUSTOMER_APPROVAL_PENDING', 'APPROVED', 'ADVANCE_PAYMENT_PENDING', 'IN_PRODUCTION', 'COMPLETED', 'SHIPPED', 'DELIVERED', 'REJECTED', 'QUOTATION_EXPIRED', 'CANCELLED']

export function CustomRequestsPage() {
  const [page, setPage] = useState(0); const [status, setStatus] = useState<CustomRequestStatus | ''>(''); const [data, setData] = useState<CustomRequestPage | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null)
  const load = useCallback(async () => { setLoading(true); setError(null); try { setData(await customArtworkService.list(page, 20, status || undefined)) } catch (cause) { setError(normalizeApiError(cause).message) } finally { setLoading(false) } }, [page, status])
  useEffect(() => { void Promise.resolve().then(load) }, [load])
  const filter = (next: string) => { setLoading(true); setPage(0); setStatus(next as CustomRequestStatus | '') }
  return <section className="commerce-page"><div className="page-heading heading-actions"><div><p className="eyebrow">Commissioned work</p><h1>My custom requests</h1><p>Follow each request from submission through quotation, production, and delivery.</p></div><Link className="button button-primary" to="/custom-requests/new">Submit new request</Link></div><div className="request-filter"><label htmlFor="request-status">Filter by status</label><select id="request-status" value={status} onChange={(e) => filter(e.target.value)}><option value="">All statuses</option>{statusOptions.map((value) => <option key={value} value={value}>{value.replaceAll('_', ' ')}</option>)}</select></div>{loading ? <LoadingState label="Loading custom requests" cards /> : error ? <ErrorState title="We couldn't load your requests" message={error} onRetry={() => void load()} /> : !data || data.content.length === 0 ? <EmptyState title={status ? 'No requests match this status' : "You haven't submitted any custom requests yet"} message={status ? 'Choose another status or view all requests.' : 'Start a request and share reference images with the artist.'} action={status ? <button className="button button-secondary" type="button" onClick={() => filter('')}>View all requests</button> : <Link className="button button-primary state-link" to="/custom-requests/new">Submit a request</Link>} /> : <><div className="request-list">{data.content.map((request) => <article className="request-card" key={request.id}><div><p className="order-card-label">Custom request #{request.id}</p><h2><Link to={`/custom-requests/${request.id}`}>{request.productType}</Link></h2><p className="request-description">{request.description}</p></div><div><p className="order-card-label">Submitted</p><time dateTime={request.createdAt}>{formatDateTime(request.createdAt)}</time></div><StatusBadge kind="request" value={request.status} /><Link className="button button-secondary" to={`/custom-requests/${request.id}`} aria-label={`View custom request ${request.id}`}>View request</Link></article>)}</div>{data.total_pages > 1 && <nav className="pagination" aria-label="Custom request pages"><button className="button button-secondary" type="button" disabled={data.page === 0} onClick={() => { setLoading(true); setPage(data.page - 1) }}>Previous</button><span>Page {data.page + 1} of {data.total_pages}</span><button className="button button-secondary" type="button" disabled={data.page + 1 >= data.total_pages} onClick={() => { setLoading(true); setPage(data.page + 1) }}>Next</button></nav>}</>}</section>
}
