import { useCallback, useEffect, useRef, useState, type ChangeEvent, type FormEvent } from 'react'
import { Link, useLocation, useParams } from 'react-router-dom'
import { StatusBadge } from '../components/commerce/StatusBadge'
import { WorkflowTimeline } from '../components/commerce/WorkflowTimeline'
import { ReferenceImageList } from '../components/customArtwork/ReferenceImageList'
import { ErrorState } from '../components/feedback/ErrorState'
import { LoadingState } from '../components/feedback/LoadingState'
import { customArtworkService } from '../services/customArtworkService'
import type { Payment, Shipment } from '../types/commerce'
import type { CustomArtworkRequest, Quotation } from '../types/customArtwork'
import { normalizeApiError } from '../utils/apiError'
import { formatCurrency, formatDate, formatDateTime, humanizeStatus } from '../utils/format'

const quotationStates = new Set(['QUOTED', 'CUSTOMER_APPROVAL_PENDING', 'APPROVED', 'ADVANCE_PAYMENT_PENDING', 'IN_PRODUCTION', 'COMPLETED', 'SHIPPED', 'DELIVERED', 'REJECTED', 'QUOTATION_EXPIRED'])

export function CustomRequestDetailPage() {
  const id = Number(useParams().id); const location = useLocation(); const newlyCreated = Boolean((location.state as { newlyCreated?: boolean } | null)?.newlyCreated)
  const [request, setRequest] = useState<CustomArtworkRequest | null>(null); const [quotation, setQuotation] = useState<Quotation | null>(null); const [payments, setPayments] = useState<Payment[]>([]); const [shipment, setShipment] = useState<Shipment | null>(null)
  const [loading, setLoading] = useState(true); const [pageError, setPageError] = useState<string | null>(null); const [quotationLoading, setQuotationLoading] = useState(false); const [quotationError, setQuotationError] = useState<string | null>(null); const [paymentLoading, setPaymentLoading] = useState(false); const [paymentError, setPaymentError] = useState<string | null>(null); const [shipmentLoading, setShipmentLoading] = useState(false); const [shipmentError, setShipmentError] = useState<string | null>(null); const [mutation, setMutation] = useState<'approve' | 'reject' | 'payment' | null>(null); const [notice, setNotice] = useState<string | null>(newlyCreated ? 'Request created. Add reference images now, or return later while it is under review.' : null)

  const loadRelated = useCallback(async (current: CustomArtworkRequest) => {
    setPaymentLoading(true); setPaymentError(null)
    void customArtworkService.listPayments(id).then(setPayments).catch((cause) => setPaymentError(normalizeApiError(cause).message)).finally(() => setPaymentLoading(false))
    if (quotationStates.has(current.status)) { setQuotationLoading(true); setQuotationError(null); void customArtworkService.getQuotation(id).then(setQuotation).catch((cause) => { const error = normalizeApiError(cause); if (error.status !== 404) setQuotationError(error.message) }).finally(() => setQuotationLoading(false)) } else setQuotation(null)
    if (current.status === 'SHIPPED' || current.status === 'DELIVERED') { setShipmentLoading(true); setShipmentError(null); void customArtworkService.getShipment(id).then(setShipment).catch((cause) => { const error = normalizeApiError(cause); if (error.status !== 404) setShipmentError(error.message) }).finally(() => setShipmentLoading(false)) } else setShipment(null)
  }, [id])
  const load = useCallback(async () => { if (!Number.isSafeInteger(id) || id <= 0) { setPageError('This custom request address is invalid.'); setLoading(false); return } setLoading(true); setPageError(null); try { const current = await customArtworkService.get(id); setRequest(current); await loadRelated(current) } catch (cause) { setPageError(normalizeApiError(cause).message) } finally { setLoading(false) } }, [id, loadRelated])
  const refreshRequest = useCallback(async () => { const current = await customArtworkService.get(id); setRequest(current) }, [id])
  useEffect(() => { void Promise.resolve().then(load) }, [load])

  const decide = async (decision: 'approve' | 'reject') => { if (!quotation || mutation) return; const wording = decision === 'approve' ? 'Approve this quotation and continue to advance payment?' : 'Reject this quotation? This decision cannot be undone.'; if (!window.confirm(wording)) return; setMutation(decision); setQuotationError(null); setNotice(null); try { await (decision === 'approve' ? customArtworkService.approveQuotation(quotation.id) : customArtworkService.rejectQuotation(quotation.id)); setNotice(`Quotation ${decision === 'approve' ? 'approved' : 'rejected'}.`); await load() } catch (cause) { const message = normalizeApiError(cause).message; await load(); setQuotationError(message) } finally { setMutation(null) } }
  const pay = async () => { if (!request || request.status !== 'APPROVED' || mutation) return; setMutation('payment'); setPaymentError(null); setNotice(null); try { const payment = await customArtworkService.initiateAdvancePayment(request.id, { paymentMethod: 'SANDBOX' }); setNotice(`Advance payment status: ${humanizeStatus(payment.status)}.`); await load() } catch (cause) { const message = normalizeApiError(cause).message; await load(); setPaymentError(message) } finally { setMutation(null) } }
  if (loading) return <LoadingState label="Loading custom request" />
  if (pageError || !request) return <ErrorState title="We couldn't load this custom request" message={pageError ?? 'Request not found.'} onRetry={() => void load()} action={<Link className="state-link" to="/custom-requests">Back to custom requests</Link>} />

  return <section className="commerce-page"><Link className="back-link" to="/custom-requests">← My custom requests</Link><div className="page-heading custom-detail-heading"><p className="eyebrow">Custom artwork request</p><h1>Request #{request.id}</h1><p>Submitted <time dateTime={request.createdAt}>{formatDateTime(request.createdAt)}</time></p><StatusBadge kind="request" value={request.status} /></div>{notice && <p className="form-alert form-alert-success" role="status">{notice}</p>}<section className="detail-panel"><h2>Progress</h2><WorkflowTimeline status={request.status} /></section><div className="custom-detail-grid"><div className="custom-detail-main"><RequestDetails request={request} /><ReferenceImages request={request} onUploaded={refreshRequest} /><QuotationPanel request={request} quotation={quotation} loading={quotationLoading} error={quotationError} mutation={mutation} onDecide={decide} /><AdvancePaymentPanel request={request} quotation={quotation} payments={payments} loading={paymentLoading} error={paymentError} mutation={mutation} onPay={pay} /></div><aside><ShipmentPanel request={request} shipment={shipment} loading={shipmentLoading} error={shipmentError} /></aside></div></section>
}

function RequestDetails({ request }: { request: CustomArtworkRequest }) { const entries = [['Product type', request.productType], ['Design theme', request.designTheme], ['Preferred colors', request.preferredColors], ['Dimensions/size', request.dimensionsSize], ['Budget range', request.budgetRange], ['Required delivery', request.requiredDeliveryDate ? formatDate(request.requiredDeliveryDate) : null], ['Additional instructions', request.additionalInstructions], ['Review notes', request.reviewNotes]]; return <section className="detail-panel"><h2>What you submitted</h2><p className="request-description-full">{request.description}</p><dl className="request-details">{entries.filter((entry) => entry[1]).map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section> }

function ReferenceImages({ request, onUploaded }: { request: CustomArtworkRequest; onUploaded: () => Promise<void> }) { const inputRef = useRef<HTMLInputElement>(null); const [file, setFile] = useState<File | null>(null); const [uploading, setUploading] = useState(false); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null); const upload = async (event: FormEvent) => { event.preventDefault(); if (!file || uploading) { if (!file) setError('Choose an image to upload.'); return } setUploading(true); setError(null); setSuccess(null); try { const image = await customArtworkService.uploadImage(request.id, file); setSuccess(`${image.originalFilename} uploaded.`); setFile(null); if (inputRef.current) inputRef.current.value = ''; await onUploaded() } catch (cause) { setError(normalizeApiError(cause).message) } finally { setUploading(false) } }; return <section className="detail-panel"><h2>Reference images</h2>{request.images.length ? <ReferenceImageList images={request.images} /> : <p>No reference images uploaded yet.</p>}<form className="upload-form" onSubmit={upload}><label htmlFor="reference-image">Add a reference image</label><input ref={inputRef} id="reference-image" type="file" accept="image/*" disabled={uploading} onChange={(event: ChangeEvent<HTMLInputElement>) => { setFile(event.target.files?.[0] ?? null); setError(null); setSuccess(null) }} />{file && <p>Selected: {file.name}</p>}<button className="button button-primary" type="submit" disabled={!file || uploading}>{uploading ? 'Uploading…' : 'Upload image'}</button>{error && <p className="form-alert form-alert-error" role="alert">{error}</p>}{success && <p className="form-alert form-alert-success" role="status">{success}</p>}</form></section> }

function QuotationPanel({ request, quotation, loading, error, mutation, onDecide }: { request: CustomArtworkRequest; quotation: Quotation | null; loading: boolean; error: string | null; mutation: string | null; onDecide: (decision: 'approve' | 'reject') => Promise<void> }) { const [renderTime] = useState(() => Date.now()); if (!quotationStates.has(request.status)) return <section className="detail-panel"><h2>Quotation</h2><p>Your request is awaiting review. A quotation will appear here after the admin reviews it.</p></section>; if (loading) return <section className="detail-panel"><h2>Quotation</h2><p role="status">Loading quotation…</p></section>; if (error || !quotation) return <section className="detail-panel"><h2>Quotation</h2><p className="form-alert form-alert-error" role="alert">{error ?? 'Quotation is not available yet.'}</p></section>; const expired = new Date(quotation.expiryAt).getTime() <= renderTime; const actionable = request.status === 'QUOTED' && quotation.status === 'PENDING' && !expired; return <section className="detail-panel"><div className="section-heading-inline"><h2>Quotation</h2><StatusBadge kind="quotation" value={quotation.status} /></div><dl className="request-details"><div><dt>Quoted amount</dt><dd>{formatCurrency(quotation.quotedAmount)}</dd></div>{quotation.advanceAmount !== null && <div><dt>Advance payment</dt><dd>{formatCurrency(quotation.advanceAmount)}</dd></div>}<div><dt>Offer expires</dt><dd><time dateTime={quotation.expiryAt}>{formatDateTime(quotation.expiryAt)}</time></dd></div>{quotation.estimatedDeliveryDate && <div><dt>Estimated delivery</dt><dd>{formatDate(quotation.estimatedDeliveryDate)}</dd></div>}{quotation.notesTerms && <div><dt>Notes and terms</dt><dd>{quotation.notesTerms}</dd></div>}</dl>{expired && quotation.status === 'PENDING' && <p className="form-alert form-alert-error" role="status">This quotation has passed its expiry time and can no longer be approved.</p>}{actionable && <div className="form-actions"><button className="button button-primary" type="button" disabled={mutation !== null} onClick={() => void onDecide('approve')}>{mutation === 'approve' ? 'Approving…' : 'Approve quotation'}</button><button className="button button-secondary" type="button" disabled={mutation !== null} onClick={() => void onDecide('reject')}>{mutation === 'reject' ? 'Rejecting…' : 'Reject quotation'}</button></div>}</section> }

function AdvancePaymentPanel({ request, quotation, payments, loading, error, mutation, onPay }: { request: CustomArtworkRequest; quotation: Quotation | null; payments: Payment[]; loading: boolean; error: string | null; mutation: string | null; onPay: () => Promise<void> }) { const successful = payments.some((payment) => payment.paymentPurpose === 'ADVANCE' && payment.status === 'SUCCESS'); const canPay = request.status === 'APPROVED' && !successful && quotation?.advanceAmount != null; return <section className="detail-panel"><div className="section-heading-inline"><h2>Advance payment</h2>{canPay && <button className="button button-primary" type="button" disabled={mutation !== null} onClick={() => void onPay()}>{mutation === 'payment' ? 'Processing…' : `Pay ${formatCurrency(quotation.advanceAmount!)}`}</button>}</div><p>The amount is fixed by the approved quotation. No card or bank details are collected by this sandbox flow.</p>{error && <p className="form-alert form-alert-error" role="alert">{error}</p>}{loading ? <p role="status">Loading payment status…</p> : payments.length === 0 ? <p>No advance payment attempts yet.</p> : <ul className="payment-list">{payments.map((payment) => <li key={payment.paymentId}><div><StatusBadge kind="payment" value={payment.status} /><strong>{formatCurrency(payment.amount)}</strong></div><p>{humanizeStatus(payment.paymentPurpose)} · {payment.paymentMethod} · {formatDateTime(payment.initiatedAt)}</p>{payment.failureReason && <p>{payment.failureReason}</p>}</li>)}</ul>}</section> }

function ShipmentPanel({ request, shipment, loading, error }: { request: CustomArtworkRequest; shipment: Shipment | null; loading: boolean; error: string | null }) { const visible = request.status === 'SHIPPED' || request.status === 'DELIVERED'; return <section className="detail-panel"><h2>Shipment</h2>{!visible ? <p>Tracking will appear after the artwork is shipped.</p> : loading ? <p role="status">Loading shipment…</p> : error ? <p className="form-alert form-alert-error" role="alert">{error}</p> : !shipment ? <p>Not yet shipped. A shipment record has not been created.</p> : <><StatusBadge kind="shipment" value={shipment.status} /><dl className="request-details shipment-details">{shipment.carrierName && <div><dt>Carrier</dt><dd>{shipment.carrierName}</dd></div>}{shipment.trackingReference && <div><dt>Tracking reference</dt><dd>{shipment.trackingReference}</dd></div>}{shipment.estimatedDeliveryDate && <div><dt>Estimated delivery</dt><dd>{formatDate(shipment.estimatedDeliveryDate)}</dd></div>}{shipment.shippedAt && <div><dt>Shipped</dt><dd>{formatDateTime(shipment.shippedAt)}</dd></div>}{shipment.deliveredAt && <div><dt>Delivered</dt><dd>{formatDateTime(shipment.deliveredAt)}</dd></div>}</dl></>}</section> }
