import { useRef, useState, type FormEvent } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { FormError } from '../components/forms/FormError'
import { FormField } from '../components/forms/FormField'
import { SubmitButton } from '../components/forms/SubmitButton'
import { customArtworkService } from '../services/customArtworkService'
import { normalizeApiError, type NormalizedApiError } from '../utils/apiError'

interface FieldErrors { productType?: string; description?: string; designTheme?: string; preferredColors?: string; dimensionsSize?: string; budgetRange?: string }

export function NewCustomRequestPage() {
  const [params] = useSearchParams(); const navigate = useNavigate(); const errorRef = useRef<HTMLDivElement>(null)
  const [productType, setProductType] = useState(params.get('productType') ?? '')
  const [description, setDescription] = useState(params.get('inspiration') ? `Inspired by: ${params.get('inspiration')}` : '')
  const [designTheme, setDesignTheme] = useState(''); const [preferredColors, setPreferredColors] = useState(''); const [dimensionsSize, setDimensionsSize] = useState(''); const [budgetRange, setBudgetRange] = useState(''); const [requiredDeliveryDate, setRequiredDeliveryDate] = useState(''); const [additionalInstructions, setAdditionalInstructions] = useState('')
  const [errors, setErrors] = useState<FieldErrors>({}); const [apiError, setApiError] = useState<NormalizedApiError | null>(null); const [submitting, setSubmitting] = useState(false)
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (submitting) return; const next: FieldErrors = {}; if (!productType.trim()) next.productType = 'Product type is required.'; else if (productType.trim().length > 100) next.productType = 'Product type must not exceed 100 characters.'; if (!description.trim()) next.description = 'Description is required.'; if (designTheme.trim().length > 200) next.designTheme = 'Design theme must not exceed 200 characters.'; if (preferredColors.trim().length > 200) next.preferredColors = 'Preferred colors must not exceed 200 characters.'; if (dimensionsSize.trim().length > 100) next.dimensionsSize = 'Dimensions/size must not exceed 100 characters.'; if (budgetRange.trim().length > 100) next.budgetRange = 'Budget range must not exceed 100 characters.'; setErrors(next); setApiError(null); if (Object.keys(next).length) return; setSubmitting(true); try { const request = await customArtworkService.create({ productType: productType.trim(), description: description.trim(), ...(designTheme.trim() && { designTheme: designTheme.trim() }), ...(preferredColors.trim() && { preferredColors: preferredColors.trim() }), ...(dimensionsSize.trim() && { dimensionsSize: dimensionsSize.trim() }), ...(budgetRange.trim() && { budgetRange: budgetRange.trim() }), ...(requiredDeliveryDate && { requiredDeliveryDate }), ...(additionalInstructions.trim() && { additionalInstructions: additionalInstructions.trim() }) }); navigate(`/custom-requests/${request.id}`, { replace: true, state: { newlyCreated: true } }) } catch (cause) { setApiError(normalizeApiError(cause)); requestAnimationFrame(() => errorRef.current?.focus()) } finally { setSubmitting(false) } }
  return <section className="commerce-page narrow-form-page"><Link className="back-link" to="/custom-requests">← My custom requests</Link><div className="page-heading"><p className="eyebrow">Made for you</p><h1>Request custom artwork</h1><p>Tell the artist what you have in mind. Required fields are marked.</p></div>{apiError && <FormError ref={errorRef} message={apiError.message} details={apiError.details} />}<form className="commerce-form custom-request-form" noValidate onSubmit={submit}><FormField id="custom-product-type" label="Product type" value={productType} onChange={(e) => setProductType(e.target.value)} error={errors.productType} maxLength={100} disabled={submitting} required /><TextArea id="custom-description" label="Description" value={description} onChange={setDescription} error={errors.description} disabled={submitting} required /><FormField id="custom-theme" label="Design theme (optional)" value={designTheme} onChange={(e) => setDesignTheme(e.target.value)} error={errors.designTheme} maxLength={200} disabled={submitting} /><FormField id="custom-colors" label="Preferred colors (optional)" value={preferredColors} onChange={(e) => setPreferredColors(e.target.value)} error={errors.preferredColors} maxLength={200} disabled={submitting} /><FormField id="custom-size" label="Dimensions or size (optional)" value={dimensionsSize} onChange={(e) => setDimensionsSize(e.target.value)} error={errors.dimensionsSize} maxLength={100} disabled={submitting} /><FormField id="custom-budget" label="Budget range (optional)" value={budgetRange} onChange={(e) => setBudgetRange(e.target.value)} error={errors.budgetRange} maxLength={100} disabled={submitting} /><FormField id="custom-date" label="Required delivery date (optional)" type="date" value={requiredDeliveryDate} onChange={(e) => setRequiredDeliveryDate(e.target.value)} disabled={submitting} /><TextArea id="custom-instructions" label="Additional instructions (optional)" value={additionalInstructions} onChange={setAdditionalInstructions} disabled={submitting} /><SubmitButton isSubmitting={submitting} idleLabel="Submit request" submittingLabel="Submitting…" /></form></section>
}

function TextArea({ id, label, value, onChange, error, disabled, required }: { id: string; label: string; value: string; onChange: (value: string) => void; error?: string; disabled: boolean; required?: boolean }) { const errorId = `${id}-error`; return <div className="form-field"><label htmlFor={id}>{label}</label><textarea id={id} value={value} onChange={(e) => onChange(e.target.value)} aria-invalid={error ? true : undefined} aria-describedby={error ? errorId : undefined} disabled={disabled} required={required} rows={5} />{error && <span className="field-error" id={errorId}>{error}</span>}</div> }
