import { screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { Route, Routes } from 'react-router-dom'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { AdminProductsPage } from '../pages/AdminProductsPage'
import { AdminInventoryPage } from '../pages/AdminInventoryPage'
import { AdminProductFormPage } from '../pages/AdminProductFormPage'
import { AdminOrderDetailPage } from '../pages/AdminOrderDetailPage'
import { adminCommerceService } from '../services/adminCommerceService'
import { renderWithRouter } from './helpers'

vi.mock('../services/adminCommerceService', () => ({ adminCommerceService: { listProducts: vi.fn(), listInventory: vi.fn(), updateInventory: vi.fn(), listCategories: vi.fn(), createProduct: vi.fn(), getProduct: vi.fn(), updateProduct: vi.fn(), getOrder: vi.fn(), getOrderPayments: vi.fn(), getOrderShipment: vi.fn(), setOrderStatus: vi.fn(), createOrderShipment: vi.fn(), setShipmentStatus: vi.fn() } }))
const product = { id: 8, name: 'Clay Vase', price: 75, product_type: 'READY_MADE' as const, category_id: 2, category_name: 'Ceramics', primary_image: null, created_at: '', status: 'ACTIVE' as const }
const products = { content: [product], page: 0, size: 20, total_elements: 1, total_pages: 1 }

describe('admin commerce', () => {
  beforeEach(() => { vi.mocked(adminCommerceService.listProducts).mockResolvedValue(products); vi.mocked(adminCommerceService.listInventory).mockResolvedValue({ content: [{ product_id: 8, quantity_on_hand: 6, updated_at: '2026-01-01T00:00:00Z' }], page: 0, size: 20, total_elements: 1, total_pages: 1 }); vi.mocked(adminCommerceService.updateInventory).mockResolvedValue({ product_id: 8, quantity_on_hand: 9, updated_at: '' }); vi.mocked(adminCommerceService.listCategories).mockResolvedValue([{ id: 2, name: 'Ceramics', description: null, status: 'ACTIVE', created_at: '' }]); vi.mocked(adminCommerceService.createProduct).mockResolvedValue({ ...product, description: null, images: [], availability: { in_stock: false }, related_products: [], updated_at: '' }) })
  it('renders the ADMIN product list', async () => { renderWithRouter(<AdminProductsPage />); expect(await screen.findByText('Clay Vase')).toBeInTheDocument(); expect(screen.getByText('Active')).toBeInTheDocument() })
  it('renders authoritative inventory and submits an accepted value', async () => { renderWithRouter(<AdminInventoryPage />); const input = await screen.findByLabelText('Quantity for product 8'); expect(input).toHaveValue(6); await userEvent.clear(input); await userEvent.type(input, '9'); await userEvent.click(screen.getByRole('button', { name: 'Save' })); await waitFor(() => expect(adminCommerceService.updateInventory).toHaveBeenCalledWith(8, 9)) })
  it('rejects invalid inventory client-side', async () => { renderWithRouter(<AdminInventoryPage />); const input = await screen.findByLabelText('Quantity for product 8'); await userEvent.clear(input); await userEvent.type(input, '-1'); expect(screen.getByRole('button', { name: 'Save' })).toBeDisabled() })
  it('navigates from successful creation to created product detail', async () => { renderWithRouter(<Routes><Route path="/admin/products/new" element={<AdminProductFormPage />} /><Route path="/admin/products/:id" element={<p>Created product detail with image management</p>} /></Routes>, { route: '/admin/products/new' }); await screen.findByRole('heading', { name: 'Create product' }); await userEvent.type(screen.getByLabelText('Name'), 'Clay Vase'); await userEvent.clear(screen.getByLabelText('Price')); await userEvent.type(screen.getByLabelText('Price'), '75'); await userEvent.click(screen.getByRole('button', { name: 'Create product' })); expect(await screen.findByText('Created product detail with image management')).toBeInTheDocument(); expect(adminCommerceService.createProduct).toHaveBeenCalled() })
  it('renders standard order and only supported forward controls', async () => { vi.mocked(adminCommerceService.getOrder).mockResolvedValue({ orderId: 44, customerId: 1, customerEmail: 'customer@example.com', status: 'CONFIRMED', shipRecipientName: 'Asha', shipLine1: '1 Main', shipLine2: null, shipCity: 'Kolkata', shipStateProvince: 'WB', shipPostalCode: '700001', shipCountry: 'India', shipPhone: null, subtotalAmount: 75, totalAmount: 75, items: [], createdAt: '2026-01-01T00:00:00Z', updatedAt: '' }); vi.mocked(adminCommerceService.getOrderPayments).mockResolvedValue([]); vi.mocked(adminCommerceService.getOrderShipment).mockResolvedValue({ id: 3, orderId: 44, customOrderRequestId: null, carrierName: 'DHL', trackingReference: 'DONE', status: 'DELIVERED', estimatedDeliveryDate: null, shippedAt: null, deliveredAt: '2026-01-02T00:00:00Z', createdAt: '' }); renderWithRouter(<Routes><Route path="/admin/orders/:id" element={<AdminOrderDetailPage />} /></Routes>, { route: '/admin/orders/44' }); expect(await screen.findByRole('heading', { name: 'Order #44' })).toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Mark Processing' })).toBeInTheDocument(); expect(screen.queryByRole('button', { name: 'Mark Delivered' })).not.toBeInTheDocument(); expect(screen.queryByRole('button', { name: 'Create shipment' })).not.toBeInTheDocument() })
})
